// Generated by apigen cli from backend/openapi.json — do not edit by hand.
// Every feature route as `api <area> <action>`; the call goes through callRoute
// (cli/src/lib/apigen-call.ts), which uses this CLI's own sign-in and client, and bad
// input through failRoute (the CLI's own error output).
import { Command } from 'commander';
import { callRoute, failRoute } from '../lib/apigen-call.js';

type Kind = 'string' | 'number' | 'boolean' | 'array' | 'json';
interface Field { name: string; kind: Kind; required: boolean; choices?: string[] }
interface Route { name: string; aliases?: string[]; method: string; path: string; summary: string; pathParams: string[]; query: Field[]; body: Field[] | null }

export const API_ROUTES: Array<{ area: string; routes: Route[] }> = [
 {
  "area": "account",
  "routes": [
   {
    "name": "marketing-media-avatar",
    "method": "GET",
    "path": "/api/v1/account/marketing-media/avatar",
    "summary": "Resolve the creator's signed S3 avatar URL via Ripllo's public uploads endpoint, then stream the bytes.",
    "pathParams": [],
    "query": [
     {
      "name": "key",
      "kind": "string",
      "required": false
     }
    ],
    "body": null
   }
  ]
 },
 {
  "area": "api-keys",
  "routes": [
   {
    "name": "create",
    "method": "POST",
    "path": "/api/v1/api-keys",
    "summary": "Create an api key",
    "pathParams": [],
    "query": [],
    "body": [
     {
      "name": "name",
      "kind": "string",
      "required": true
     }
    ]
   },
   {
    "name": "delete",
    "method": "DELETE",
    "path": "/api/v1/api-keys/{id}",
    "summary": "Delete an api key",
    "pathParams": [
     "id"
    ],
    "query": [],
    "body": null
   },
   {
    "name": "list",
    "method": "GET",
    "path": "/api/v1/api-keys",
    "summary": "List api keys",
    "pathParams": [],
    "query": [],
    "body": null
   }
  ]
 },
 {
  "area": "audit-log",
  "routes": [
   {
    "name": "list",
    "method": "GET",
    "path": "/api/v1/audit-log",
    "summary": "List audit log",
    "pathParams": [],
    "query": [
     {
      "name": "type",
      "kind": "string",
      "required": false
     }
    ],
    "body": null
   }
  ]
 },
 {
  "area": "billing",
  "routes": [
   {
    "name": "cancel",
    "method": "POST",
    "path": "/api/v1/billing/cancel",
    "summary": "Downgrade to Free.",
    "pathParams": [],
    "query": [],
    "body": null
   },
   {
    "name": "checkout",
    "method": "POST",
    "path": "/api/v1/billing/checkout",
    "summary": "POST /checkout {tier} — create a Plugipay hosted checkout session for a paid tier; the browser redirects to data.hostedUrl.",
    "pathParams": [],
    "query": [],
    "body": [
     {
      "name": "tier",
      "kind": "string",
      "required": true,
      "choices": [
       "free",
       "starter",
       "growth",
       "business"
      ]
     },
     {
      "name": "currency",
      "kind": "string",
      "required": false,
      "choices": [
       "IDR",
       "USD"
      ]
     }
    ]
   },
   {
    "name": "list",
    "method": "GET",
    "path": "/api/v1/billing",
    "summary": "Current subscription (free default when no row) + the tier table the portal renders. `effectiveTier` is what the freemium gate actually honors (lapsed/canceled rows fall back to free).",
    "pathParams": [],
    "query": [],
    "body": null
   }
  ]
 },
 {
  "area": "certifications",
  "routes": [
   {
    "name": "create",
    "method": "POST",
    "path": "/api/v1/certifications",
    "summary": "Create a certification",
    "pathParams": [],
    "query": [],
    "body": [
     {
      "name": "name",
      "kind": "string",
      "required": true
     },
     {
      "name": "issuer",
      "kind": "string",
      "required": true
     },
     {
      "name": "issuedAt",
      "kind": "string",
      "required": false
     },
     {
      "name": "credentialUrl",
      "kind": "string",
      "required": false
     },
     {
      "name": "imageUrl",
      "kind": "string",
      "required": false
     },
     {
      "name": "published",
      "kind": "boolean",
      "required": false
     },
     {
      "name": "sortOrder",
      "kind": "number",
      "required": false
     }
    ]
   },
   {
    "name": "delete",
    "method": "DELETE",
    "path": "/api/v1/certifications/{id}",
    "summary": "Delete a certification",
    "pathParams": [
     "id"
    ],
    "query": [],
    "body": null
   },
   {
    "name": "get",
    "method": "GET",
    "path": "/api/v1/certifications/{id}",
    "summary": "Get a certification",
    "pathParams": [
     "id"
    ],
    "query": [],
    "body": null
   },
   {
    "name": "list",
    "method": "GET",
    "path": "/api/v1/certifications",
    "summary": "List certifications",
    "pathParams": [],
    "query": [],
    "body": null
   },
   {
    "name": "update",
    "method": "PATCH",
    "path": "/api/v1/certifications/{id}",
    "summary": "Update a certification",
    "pathParams": [
     "id"
    ],
    "query": [],
    "body": [
     {
      "name": "name",
      "kind": "string",
      "required": false
     },
     {
      "name": "issuer",
      "kind": "string",
      "required": false
     },
     {
      "name": "issuedAt",
      "kind": "string",
      "required": false
     },
     {
      "name": "credentialUrl",
      "kind": "string",
      "required": false
     },
     {
      "name": "imageUrl",
      "kind": "string",
      "required": false
     },
     {
      "name": "published",
      "kind": "boolean",
      "required": false
     },
     {
      "name": "sortOrder",
      "kind": "number",
      "required": false
     }
    ]
   }
  ]
 },
 {
  "area": "client",
  "routes": [
   {
    "name": "get-orders",
    "method": "GET",
    "path": "/api/v1/client/orders/{id}",
    "summary": "Get an order",
    "pathParams": [
     "id"
    ],
    "query": [],
    "body": null,
    "aliases": [
     "orders-2"
    ]
   },
   {
    "name": "orders",
    "method": "GET",
    "path": "/api/v1/client/orders",
    "summary": "List orders",
    "pathParams": [],
    "query": [],
    "body": null
   },
   {
    "name": "orders-invoice-pdf",
    "method": "GET",
    "path": "/api/v1/client/orders/{id}/invoice.pdf",
    "summary": "The order's Plugipay invoice PDF for the signed-in portal client — same stream as the tokenized buyer route; the session + the client-order scope are the credential. 404 while no invoice.",
    "pathParams": [
     "id"
    ],
    "query": [],
    "body": null
   },
   {
    "name": "orders-messages",
    "method": "POST",
    "path": "/api/v1/client/orders/{id}/messages",
    "summary": "Messages an order",
    "pathParams": [
     "id"
    ],
    "query": [],
    "body": [
     {
      "name": "body",
      "kind": "string",
      "required": true
     },
     {
      "name": "attachments",
      "kind": "array",
      "required": false
     }
    ]
   },
   {
    "name": "orders-messages-stream",
    "method": "GET",
    "path": "/api/v1/client/orders/{id}/messages/stream",
    "summary": "SSE: realtime nudge for the buyer portal.",
    "pathParams": [
     "id"
    ],
    "query": [],
    "body": null
   },
   {
    "name": "orders-unread-count",
    "method": "GET",
    "path": "/api/v1/client/orders/unread-count",
    "summary": "Aggregate unread count for the buyer-portal nav badge.",
    "pathParams": [],
    "query": [],
    "body": null
   },
   {
    "name": "profile",
    "method": "GET",
    "path": "/api/v1/client/profile",
    "summary": "List profile",
    "pathParams": [],
    "query": [],
    "body": null
   },
   {
    "name": "uploads-attachment",
    "method": "POST",
    "path": "/api/v1/client/uploads/attachment",
    "summary": "Chat attachment upload (buyer portal).",
    "pathParams": [],
    "query": [],
    "body": null
   }
  ]
 },
 {
  "area": "client-logos",
  "routes": [
   {
    "name": "create",
    "method": "POST",
    "path": "/api/v1/client-logos",
    "summary": "Create a client logo",
    "pathParams": [],
    "query": [],
    "body": [
     {
      "name": "name",
      "kind": "string",
      "required": true
     },
     {
      "name": "logoUrl",
      "kind": "string",
      "required": true
     },
     {
      "name": "url",
      "kind": "string",
      "required": false
     },
     {
      "name": "published",
      "kind": "boolean",
      "required": false
     },
     {
      "name": "sortOrder",
      "kind": "number",
      "required": false
     }
    ]
   },
   {
    "name": "delete",
    "method": "DELETE",
    "path": "/api/v1/client-logos/{id}",
    "summary": "Delete a client logo",
    "pathParams": [
     "id"
    ],
    "query": [],
    "body": null
   },
   {
    "name": "get",
    "method": "GET",
    "path": "/api/v1/client-logos/{id}",
    "summary": "Get a client logo",
    "pathParams": [
     "id"
    ],
    "query": [],
    "body": null
   },
   {
    "name": "list",
    "method": "GET",
    "path": "/api/v1/client-logos",
    "summary": "List client logos",
    "pathParams": [],
    "query": [],
    "body": null
   },
   {
    "name": "update",
    "method": "PATCH",
    "path": "/api/v1/client-logos/{id}",
    "summary": "Update a client logo",
    "pathParams": [
     "id"
    ],
    "query": [],
    "body": [
     {
      "name": "name",
      "kind": "string",
      "required": false
     },
     {
      "name": "logoUrl",
      "kind": "string",
      "required": false
     },
     {
      "name": "url",
      "kind": "string",
      "required": false
     },
     {
      "name": "published",
      "kind": "boolean",
      "required": false
     },
     {
      "name": "sortOrder",
      "kind": "number",
      "required": false
     }
    ]
   }
  ]
 },
 {
  "area": "domains",
  "routes": [
   {
    "name": "create",
    "method": "POST",
    "path": "/api/v1/domains",
    "summary": "Create a domain",
    "pathParams": [],
    "query": [],
    "body": [
     {
      "name": "domain",
      "kind": "string",
      "required": true
     }
    ]
   },
   {
    "name": "delete",
    "method": "DELETE",
    "path": "/api/v1/domains/{id}",
    "summary": "Delete a domain",
    "pathParams": [
     "id"
    ],
    "query": [],
    "body": null
   },
   {
    "name": "list",
    "method": "GET",
    "path": "/api/v1/domains",
    "summary": "List domains",
    "pathParams": [],
    "query": [],
    "body": null
   },
   {
    "name": "verify",
    "method": "POST",
    "path": "/api/v1/domains/{id}/verify",
    "summary": "Verify a domain",
    "pathParams": [
     "id"
    ],
    "query": [],
    "body": null
   }
  ]
 },
 {
  "area": "fulfillment",
  "routes": [
   {
    "name": "create-licenses",
    "method": "POST",
    "path": "/api/v1/fulfillment/licenses",
    "summary": "Create a license",
    "pathParams": [],
    "query": [],
    "body": [
     {
      "name": "productId",
      "kind": "string",
      "required": true
     },
     {
      "name": "customerId",
      "kind": "string",
      "required": true
     },
     {
      "name": "maxActivations",
      "kind": "number",
      "required": false
     },
     {
      "name": "expiresAt",
      "kind": "string",
      "required": false
     }
    ]
   },
   {
    "name": "create-shipments",
    "method": "POST",
    "path": "/api/v1/fulfillment/shipments",
    "summary": "Create a shipment",
    "pathParams": [],
    "query": [],
    "body": [
     {
      "name": "customerId",
      "kind": "string",
      "required": false
     },
     {
      "name": "customerEmail",
      "kind": "string",
      "required": false
     },
     {
      "name": "courierCode",
      "kind": "string",
      "required": true
     },
     {
      "name": "courierServiceCode",
      "kind": "string",
      "required": true
     },
     {
      "name": "courierType",
      "kind": "string",
      "required": false
     },
     {
      "name": "price",
      "kind": "number",
      "required": false
     },
     {
      "name": "insured",
      "kind": "boolean",
      "required": false
     },
     {
      "name": "insurance",
      "kind": "number",
      "required": false
     },
     {
      "name": "destination",
      "kind": "json",
      "required": true
     },
     {
      "name": "items",
      "kind": "array",
      "required": true
     }
    ]
   },
   {
    "name": "create-warehouses",
    "method": "POST",
    "path": "/api/v1/fulfillment/warehouses",
    "summary": "Create a warehouse",
    "pathParams": [],
    "query": [],
    "body": [
     {
      "name": "name",
      "kind": "string",
      "required": true
     },
     {
      "name": "address",
      "kind": "string",
      "required": false
     },
     {
      "name": "city",
      "kind": "string",
      "required": false
     },
     {
      "name": "postal",
      "kind": "string",
      "required": false
     },
     {
      "name": "phone",
      "kind": "string",
      "required": false
     },
     {
      "name": "isDefault",
      "kind": "boolean",
      "required": false
     }
    ]
   },
   {
    "name": "customers",
    "method": "GET",
    "path": "/api/v1/fulfillment/customers",
    "summary": "List customers",
    "pathParams": [],
    "query": [
     {
      "name": "limit",
      "kind": "string",
      "required": false
     },
     {
      "name": "q",
      "kind": "string",
      "required": false
     }
    ],
    "body": null
   },
   {
    "name": "delete-warehouses",
    "method": "DELETE",
    "path": "/api/v1/fulfillment/warehouses/{id}",
    "summary": "Delete a warehouse",
    "pathParams": [
     "id"
    ],
    "query": [],
    "body": null
   },
   {
    "name": "deliveries",
    "method": "GET",
    "path": "/api/v1/fulfillment/deliveries",
    "summary": "List deliveries",
    "pathParams": [],
    "query": [],
    "body": null
   },
   {
    "name": "get-deliveries",
    "method": "GET",
    "path": "/api/v1/fulfillment/deliveries/{id}",
    "summary": "Get a delivery",
    "pathParams": [
     "id"
    ],
    "query": [],
    "body": null,
    "aliases": [
     "deliveries-2"
    ]
   },
   {
    "name": "get-shipments",
    "method": "GET",
    "path": "/api/v1/fulfillment/shipments/{id}",
    "summary": "Get a shipment",
    "pathParams": [
     "id"
    ],
    "query": [],
    "body": null,
    "aliases": [
     "shipments-2"
    ]
   },
   {
    "name": "inventory-adjust",
    "method": "POST",
    "path": "/api/v1/fulfillment/inventory/adjust",
    "summary": "Create an adjust",
    "pathParams": [],
    "query": [],
    "body": [
     {
      "name": "variantId",
      "kind": "string",
      "required": true
     },
     {
      "name": "warehouseId",
      "kind": "string",
      "required": true
     },
     {
      "name": "delta",
      "kind": "number",
      "required": true
     },
     {
      "name": "reason",
      "kind": "string",
      "required": true,
      "choices": [
       "manual_adjust",
       "refund_restock",
       "transfer_in",
       "transfer_out",
       "damaged",
       "returned_to_supplier",
       "initial_stock",
       "import"
      ]
     },
     {
      "name": "note",
      "kind": "string",
      "required": false
     }
    ]
   },
   {
    "name": "inventory-movements",
    "method": "GET",
    "path": "/api/v1/fulfillment/inventory/movements",
    "summary": "List movements",
    "pathParams": [],
    "query": [
     {
      "name": "variantId",
      "kind": "string",
      "required": false
     }
    ],
    "body": null
   },
   {
    "name": "inventory-products",
    "method": "GET",
    "path": "/api/v1/fulfillment/inventory/products",
    "summary": "List products",
    "pathParams": [],
    "query": [],
    "body": null
   },
   {
    "name": "inventory-stock",
    "method": "GET",
    "path": "/api/v1/fulfillment/inventory/stock",
    "summary": "List stock",
    "pathParams": [],
    "query": [
     {
      "name": "variantId",
      "kind": "string",
      "required": false
     }
    ],
    "body": null
   },
   {
    "name": "licenses",
    "method": "GET",
    "path": "/api/v1/fulfillment/licenses",
    "summary": "List licenses",
    "pathParams": [],
    "query": [],
    "body": null
   },
   {
    "name": "licenses-revoke",
    "method": "POST",
    "path": "/api/v1/fulfillment/licenses/{id}/revoke",
    "summary": "Revoke a license",
    "pathParams": [
     "id"
    ],
    "query": [],
    "body": null
   },
   {
    "name": "licenses-validate",
    "method": "GET",
    "path": "/api/v1/fulfillment/licenses/validate",
    "summary": "List validate",
    "pathParams": [],
    "query": [
     {
      "name": "key",
      "kind": "string",
      "required": true
     },
     {
      "name": "productId",
      "kind": "string",
      "required": false
     }
    ],
    "body": null
   },
   {
    "name": "shipments",
    "method": "GET",
    "path": "/api/v1/fulfillment/shipments",
    "summary": "List shipments",
    "pathParams": [],
    "query": [
     {
      "name": "status",
      "kind": "string",
      "required": false
     }
    ],
    "body": null
   },
   {
    "name": "shipments-cancel",
    "method": "POST",
    "path": "/api/v1/fulfillment/shipments/{id}/cancel",
    "summary": "Cancel a shipment",
    "pathParams": [
     "id"
    ],
    "query": [],
    "body": [
     {
      "name": "reason",
      "kind": "string",
      "required": false
     }
    ]
   },
   {
    "name": "shipments-confirm-pickup",
    "method": "POST",
    "path": "/api/v1/fulfillment/shipments/{id}/confirm-pickup",
    "summary": "Confirm pickup a shipment",
    "pathParams": [
     "id"
    ],
    "query": [],
    "body": null
   },
   {
    "name": "shipments-label",
    "method": "GET",
    "path": "/api/v1/fulfillment/shipments/{id}/label",
    "summary": "List label",
    "pathParams": [
     "id"
    ],
    "query": [],
    "body": null
   },
   {
    "name": "shipping-couriers",
    "method": "GET",
    "path": "/api/v1/fulfillment/shipping/couriers",
    "summary": "List couriers",
    "pathParams": [],
    "query": [],
    "body": null
   },
   {
    "name": "shipping-credits",
    "method": "GET",
    "path": "/api/v1/fulfillment/shipping-credits",
    "summary": "List shipping credits",
    "pathParams": [],
    "query": [],
    "body": null
   },
   {
    "name": "shipping-credits-topup",
    "method": "POST",
    "path": "/api/v1/fulfillment/shipping-credits/topup",
    "summary": "Create a topup",
    "pathParams": [],
    "query": [],
    "body": [
     {
      "name": "amount",
      "kind": "number",
      "required": true
     }
    ]
   },
   {
    "name": "shipping-credits-transactions",
    "method": "GET",
    "path": "/api/v1/fulfillment/shipping-credits/transactions",
    "summary": "List transactions",
    "pathParams": [],
    "query": [
     {
      "name": "cursor",
      "kind": "string",
      "required": false
     },
     {
      "name": "limit",
      "kind": "string",
      "required": false
     }
    ],
    "body": null
   },
   {
    "name": "shipping-origin",
    "method": "GET",
    "path": "/api/v1/fulfillment/shipping/origin",
    "summary": "List origin",
    "pathParams": [],
    "query": [],
    "body": null
   },
   {
    "name": "shipping-rates",
    "method": "POST",
    "path": "/api/v1/fulfillment/shipping/rates",
    "summary": "Create a rate",
    "pathParams": [],
    "query": [],
    "body": [
     {
      "name": "destination",
      "kind": "string",
      "required": false
     },
     {
      "name": "insurance",
      "kind": "string",
      "required": false
     },
     {
      "name": "items",
      "kind": "string",
      "required": false
     }
    ]
   },
   {
    "name": "shipping-track",
    "method": "GET",
    "path": "/api/v1/fulfillment/shipping/track/{waybillId}",
    "summary": "Public buyer tracking lives on fulkruma.com — keep the route present so the chrome never 404s, but redirect callers to the canonical tracker.",
    "pathParams": [
     "waybillId"
    ],
    "query": [],
    "body": null
   },
   {
    "name": "update-shipping-origin",
    "method": "PATCH",
    "path": "/api/v1/fulfillment/shipping/origin",
    "summary": "Update origin",
    "pathParams": [],
    "query": [],
    "body": []
   },
   {
    "name": "update-warehouses",
    "method": "PATCH",
    "path": "/api/v1/fulfillment/warehouses/{id}",
    "summary": "Update a warehouse",
    "pathParams": [
     "id"
    ],
    "query": [],
    "body": [
     {
      "name": "name",
      "kind": "string",
      "required": false
     },
     {
      "name": "address",
      "kind": "string",
      "required": false
     },
     {
      "name": "city",
      "kind": "string",
      "required": false
     },
     {
      "name": "postal",
      "kind": "string",
      "required": false
     },
     {
      "name": "phone",
      "kind": "string",
      "required": false
     },
     {
      "name": "isDefault",
      "kind": "boolean",
      "required": false
     }
    ]
   },
   {
    "name": "warehouses",
    "method": "GET",
    "path": "/api/v1/fulfillment/warehouses",
    "summary": "List warehouses",
    "pathParams": [],
    "query": [],
    "body": null
   }
  ]
 },
 {
  "area": "gift-cards",
  "routes": [
   {
    "name": "create",
    "method": "POST",
    "path": "/api/v1/gift-cards",
    "summary": "Create a gift card",
    "pathParams": [],
    "query": [],
    "body": [
     {
      "name": "amount",
      "kind": "number",
      "required": true
     },
     {
      "name": "customerId",
      "kind": "string",
      "required": false
     },
     {
      "name": "code",
      "kind": "string",
      "required": false
     },
     {
      "name": "expiresAt",
      "kind": "string",
      "required": false
     },
     {
      "name": "note",
      "kind": "string",
      "required": false
     }
    ]
   },
   {
    "name": "get",
    "method": "GET",
    "path": "/api/v1/gift-cards/{code}",
    "summary": "Get a gift card",
    "pathParams": [
     "code"
    ],
    "query": [],
    "body": null
   },
   {
    "name": "list",
    "method": "GET",
    "path": "/api/v1/gift-cards",
    "summary": "List gift cards",
    "pathParams": [],
    "query": [
     {
      "name": "status",
      "kind": "string",
      "required": false,
      "choices": [
       "active",
       "redeemed",
       "void",
       "expired"
      ]
     },
     {
      "name": "customerId",
      "kind": "string",
      "required": false
     },
     {
      "name": "limit",
      "kind": "number",
      "required": false
     }
    ],
    "body": null
   },
   {
    "name": "redeem",
    "method": "POST",
    "path": "/api/v1/gift-cards/{id}/redeem",
    "summary": "Redeem a gift card",
    "pathParams": [
     "id"
    ],
    "query": [],
    "body": [
     {
      "name": "amount",
      "kind": "number",
      "required": true
     },
     {
      "name": "externalRef",
      "kind": "string",
      "required": false
     },
     {
      "name": "checkoutSessionId",
      "kind": "string",
      "required": false
     },
     {
      "name": "note",
      "kind": "string",
      "required": false
     }
    ]
   },
   {
    "name": "topup",
    "method": "POST",
    "path": "/api/v1/gift-cards/{id}/topup",
    "summary": "Topup a gift card",
    "pathParams": [
     "id"
    ],
    "query": [],
    "body": [
     {
      "name": "amount",
      "kind": "number",
      "required": true
     },
     {
      "name": "externalRef",
      "kind": "string",
      "required": false
     },
     {
      "name": "note",
      "kind": "string",
      "required": false
     }
    ]
   },
   {
    "name": "void",
    "method": "POST",
    "path": "/api/v1/gift-cards/{id}/void",
    "summary": "Void a gift card",
    "pathParams": [
     "id"
    ],
    "query": [],
    "body": [
     {
      "name": "note",
      "kind": "string",
      "required": false
     }
    ]
   }
  ]
 },
 {
  "area": "ledger",
  "routes": [
   {
    "name": "balance",
    "method": "GET",
    "path": "/api/v1/ledger/balance",
    "summary": "List balance",
    "pathParams": [],
    "query": [],
    "body": null
   },
   {
    "name": "entries",
    "method": "GET",
    "path": "/api/v1/ledger/entries",
    "summary": "List entries",
    "pathParams": [],
    "query": [
     {
      "name": "limit",
      "kind": "number",
      "required": false
     },
     {
      "name": "cursor",
      "kind": "string",
      "required": false
     },
     {
      "name": "code",
      "kind": "string",
      "required": false
     },
     {
      "name": "sourceType",
      "kind": "string",
      "required": false
     },
     {
      "name": "sourceId",
      "kind": "string",
      "required": false
     }
    ],
    "body": null
   }
  ]
 },
 {
  "area": "legal",
  "routes": [
   {
    "name": "delete",
    "method": "DELETE",
    "path": "/api/v1/legal/{slug}",
    "summary": "Revert to the template default by removing the seller's override.",
    "pathParams": [
     "slug"
    ],
    "query": [],
    "body": null
   },
   {
    "name": "get",
    "method": "GET",
    "path": "/api/v1/legal/{slug}",
    "summary": "Single override for the editor (null = template).",
    "pathParams": [
     "slug"
    ],
    "query": [],
    "body": null
   },
   {
    "name": "list",
    "method": "GET",
    "path": "/api/v1/legal",
    "summary": "Every saved override for this seller.",
    "pathParams": [],
    "query": [],
    "body": null
   },
   {
    "name": "set",
    "method": "PUT",
    "path": "/api/v1/legal/{slug}",
    "summary": "Upsert.",
    "pathParams": [
     "slug"
    ],
    "query": [],
    "body": [
     {
      "name": "title",
      "kind": "string",
      "required": true
     },
     {
      "name": "body",
      "kind": "string",
      "required": true
     }
    ]
   }
  ]
 },
 {
  "area": "me",
  "routes": [
   {
    "name": "list",
    "method": "GET",
    "path": "/api/v1/me",
    "summary": "List me",
    "pathParams": [],
    "query": [],
    "body": null
   }
  ]
 },
 {
  "area": "modules",
  "routes": [
   {
    "name": "create",
    "method": "POST",
    "path": "/api/v1/modules",
    "summary": "Create a module",
    "pathParams": [],
    "query": [],
    "body": [
     {
      "name": "module",
      "kind": "string",
      "required": true,
      "choices": [
       "payment",
       "marketing",
       "fulfillment"
      ]
     },
     {
      "name": "enabled",
      "kind": "boolean",
      "required": true
     }
    ]
   },
   {
    "name": "list",
    "method": "GET",
    "path": "/api/v1/modules",
    "summary": "List modules",
    "pathParams": [],
    "query": [],
    "body": null
   },
   {
    "name": "update",
    "method": "PATCH",
    "path": "/api/v1/modules",
    "summary": "Update modules",
    "pathParams": [],
    "query": [],
    "body": [
     {
      "name": "payment",
      "kind": "boolean",
      "required": false
     },
     {
      "name": "marketing",
      "kind": "boolean",
      "required": false
     },
     {
      "name": "fulfillment",
      "kind": "boolean",
      "required": false
     }
    ]
   }
  ]
 },
 {
  "area": "orders",
  "routes": [
   {
    "name": "confirm-payment",
    "method": "POST",
    "path": "/api/v1/orders/{id}/confirm-payment",
    "summary": "Confirm payment an order",
    "pathParams": [
     "id"
    ],
    "query": [],
    "body": null
   },
   {
    "name": "delete-payments",
    "method": "DELETE",
    "path": "/api/v1/orders/{id}/payments",
    "summary": "Payments an order",
    "pathParams": [
     "id"
    ],
    "query": [],
    "body": null
   },
   {
    "name": "get",
    "method": "GET",
    "path": "/api/v1/orders/{id}",
    "summary": "Get an order",
    "pathParams": [
     "id"
    ],
    "query": [],
    "body": null
   },
   {
    "name": "invoice",
    "method": "POST",
    "path": "/api/v1/orders/{id}/invoice",
    "summary": "Invoice an order",
    "pathParams": [
     "id"
    ],
    "query": [],
    "body": null
   },
   {
    "name": "invoice-pdf",
    "method": "GET",
    "path": "/api/v1/orders/{id}/invoice.pdf",
    "summary": "List invoice.pdf",
    "pathParams": [
     "id"
    ],
    "query": [],
    "body": null
   },
   {
    "name": "invoice-send",
    "method": "POST",
    "path": "/api/v1/orders/{id}/invoice/send",
    "summary": "Create a send",
    "pathParams": [
     "id"
    ],
    "query": [],
    "body": null
   },
   {
    "name": "list",
    "method": "GET",
    "path": "/api/v1/orders",
    "summary": "List orders",
    "pathParams": [],
    "query": [
     {
      "name": "status",
      "kind": "string",
      "required": false,
      "choices": [
       "requested",
       "confirmed",
       "declined",
       "in_progress",
       "delivered",
       "completed",
       "canceled",
       "all"
      ]
     },
     {
      "name": "paymentStatus",
      "kind": "string",
      "required": false,
      "choices": [
       "unpaid",
       "payment_claimed",
       "payment_confirmed",
       "all"
      ]
     },
     {
      "name": "serviceId",
      "kind": "string",
      "required": false
     },
     {
      "name": "q",
      "kind": "string",
      "required": false
     },
     {
      "name": "limit",
      "kind": "number",
      "required": false
     },
     {
      "name": "cursor",
      "kind": "string",
      "required": false
     }
    ],
    "body": null
   },
   {
    "name": "messages",
    "method": "POST",
    "path": "/api/v1/orders/{id}/messages",
    "summary": "Messages an order",
    "pathParams": [
     "id"
    ],
    "query": [],
    "body": [
     {
      "name": "body",
      "kind": "string",
      "required": true
     },
     {
      "name": "isInternal",
      "kind": "boolean",
      "required": false
     },
     {
      "name": "authorName",
      "kind": "string",
      "required": false
     },
     {
      "name": "attachments",
      "kind": "array",
      "required": false
     }
    ]
   },
   {
    "name": "messages-stream",
    "method": "GET",
    "path": "/api/v1/orders/{id}/messages/stream",
    "summary": "SSE: realtime nudge when a message lands on this order (seller side).",
    "pathParams": [
     "id"
    ],
    "query": [],
    "body": null
   },
   {
    "name": "payments",
    "method": "GET",
    "path": "/api/v1/orders/{id}/payments",
    "summary": "List payments",
    "pathParams": [
     "id"
    ],
    "query": [],
    "body": null
   },
   {
    "name": "payments-confirm",
    "method": "POST",
    "path": "/api/v1/orders/{id}/payments/{paymentId}/confirm",
    "summary": "Manual per-installment confirm (the seller checked their bank / the proof).",
    "pathParams": [
     "id",
     "paymentId"
    ],
    "query": [],
    "body": null
   },
   {
    "name": "payments-proof",
    "method": "GET",
    "path": "/api/v1/orders/{id}/payments/{paymentId}/proof",
    "summary": "The buyer's per-installment proof image (uploaded on the public tokenized surface) — mirrors GET /orders/:id/proof.",
    "pathParams": [
     "id",
     "paymentId"
    ],
    "query": [],
    "body": null
   },
   {
    "name": "proof",
    "method": "GET",
    "path": "/api/v1/orders/{id}/proof",
    "summary": "The buyer's payment-proof image (uploaded on the public surface).",
    "pathParams": [
     "id"
    ],
    "query": [],
    "body": null
   },
   {
    "name": "quote-items",
    "method": "GET",
    "path": "/api/v1/orders/{id}/quote-items",
    "summary": "List quote items",
    "pathParams": [
     "id"
    ],
    "query": [],
    "body": null
   },
   {
    "name": "set-payments",
    "method": "PUT",
    "path": "/api/v1/orders/{id}/payments",
    "summary": "Payments an order",
    "pathParams": [
     "id"
    ],
    "query": [],
    "body": [
     {
      "name": "installments",
      "kind": "array",
      "required": true
     }
    ]
   },
   {
    "name": "set-quote-items",
    "method": "PUT",
    "path": "/api/v1/orders/{id}/quote-items",
    "summary": "Quote items an order",
    "pathParams": [
     "id"
    ],
    "query": [],
    "body": [
     {
      "name": "items",
      "kind": "array",
      "required": true
     }
    ]
   },
   {
    "name": "unread-count",
    "method": "GET",
    "path": "/api/v1/orders/unread-count",
    "summary": "Aggregate unread-message count for the seller's nav badge.",
    "pathParams": [],
    "query": [],
    "body": null
   },
   {
    "name": "update",
    "method": "PATCH",
    "path": "/api/v1/orders/{id}",
    "summary": "Update an order",
    "pathParams": [
     "id"
    ],
    "query": [],
    "body": [
     {
      "name": "status",
      "kind": "string",
      "required": false,
      "choices": [
       "requested",
       "confirmed",
       "declined",
       "in_progress",
       "delivered",
       "completed",
       "canceled"
      ]
     },
     {
      "name": "quotedPriceIdr",
      "kind": "number",
      "required": false
     }
    ]
   }
  ]
 },
 {
  "area": "payouts",
  "routes": [
   {
    "name": "balance",
    "method": "GET",
    "path": "/api/v1/payouts/balance",
    "summary": "List balance",
    "pathParams": [],
    "query": [],
    "body": null
   },
   {
    "name": "bank-account",
    "method": "GET",
    "path": "/api/v1/payouts/bank-account",
    "summary": "List bank account",
    "pathParams": [],
    "query": [],
    "body": null
   },
   {
    "name": "cancel",
    "method": "POST",
    "path": "/api/v1/payouts/{id}/cancel",
    "summary": "Cancel a payout",
    "pathParams": [
     "id"
    ],
    "query": [],
    "body": null
   },
   {
    "name": "create",
    "method": "POST",
    "path": "/api/v1/payouts",
    "summary": "Create a payout",
    "pathParams": [],
    "query": [],
    "body": [
     {
      "name": "amount",
      "kind": "number",
      "required": true
     },
     {
      "name": "currency",
      "kind": "string",
      "required": false,
      "choices": [
       "IDR"
      ]
     },
     {
      "name": "bankCode",
      "kind": "string",
      "required": false
     },
     {
      "name": "bankName",
      "kind": "string",
      "required": false
     },
     {
      "name": "bankAccountNumber",
      "kind": "string",
      "required": false
     },
     {
      "name": "bankAccountHolder",
      "kind": "string",
      "required": false
     },
     {
      "name": "note",
      "kind": "string",
      "required": false
     }
    ]
   },
   {
    "name": "get",
    "method": "GET",
    "path": "/api/v1/payouts/{id}",
    "summary": "Single payout — registered after /balance + /bank-account so the static paths win.",
    "pathParams": [
     "id"
    ],
    "query": [],
    "body": null
   },
   {
    "name": "list",
    "method": "GET",
    "path": "/api/v1/payouts",
    "summary": "List payouts",
    "pathParams": [],
    "query": [
     {
      "name": "limit",
      "kind": "number",
      "required": false
     },
     {
      "name": "cursor",
      "kind": "string",
      "required": false
     },
     {
      "name": "status",
      "kind": "string",
      "required": false,
      "choices": [
       "pending",
       "in_transit",
       "paid",
       "failed",
       "cancelled"
      ]
     }
    ],
    "body": null
   },
   {
    "name": "mark-failed",
    "method": "POST",
    "path": "/api/v1/payouts/{id}/mark-failed",
    "summary": "Mark failed a payout",
    "pathParams": [
     "id"
    ],
    "query": [],
    "body": [
     {
      "name": "failureReason",
      "kind": "string",
      "required": true
     }
    ]
   },
   {
    "name": "mark-in-transit",
    "method": "POST",
    "path": "/api/v1/payouts/{id}/mark-in-transit",
    "summary": "Mark in transit a payout",
    "pathParams": [
     "id"
    ],
    "query": [],
    "body": [
     {
      "name": "reference",
      "kind": "string",
      "required": false
     }
    ]
   },
   {
    "name": "mark-paid",
    "method": "POST",
    "path": "/api/v1/payouts/{id}/mark-paid",
    "summary": "Mark paid a payout",
    "pathParams": [
     "id"
    ],
    "query": [],
    "body": [
     {
      "name": "reference",
      "kind": "string",
      "required": false
     }
    ]
   },
   {
    "name": "update-bank-account",
    "method": "PATCH",
    "path": "/api/v1/payouts/bank-account",
    "summary": "Update bank account",
    "pathParams": [],
    "query": [],
    "body": [
     {
      "name": "bankCode",
      "kind": "string",
      "required": false
     },
     {
      "name": "bankName",
      "kind": "string",
      "required": true
     },
     {
      "name": "bankAccountNumber",
      "kind": "string",
      "required": true
     },
     {
      "name": "bankAccountHolder",
      "kind": "string",
      "required": true
     }
    ]
   }
  ]
 },
 {
  "area": "plugipay",
  "routes": [
   {
    "name": "invoices-html",
    "method": "GET",
    "path": "/api/v1/plugipay/invoices/{id}/html",
    "summary": "List html",
    "pathParams": [
     "id"
    ],
    "query": [],
    "body": null
   },
   {
    "name": "invoices-pdf",
    "method": "GET",
    "path": "/api/v1/plugipay/invoices/{id}/pdf",
    "summary": "Binary invoice passthroughs — PDF + HTML preview.",
    "pathParams": [
     "id"
    ],
    "query": [],
    "body": null
   },
   {
    "name": "receipts-escpos",
    "method": "GET",
    "path": "/api/v1/plugipay/receipts/{id}/escpos",
    "summary": "List escpos",
    "pathParams": [
     "id"
    ],
    "query": [
     {
      "name": "width",
      "kind": "string",
      "required": false
     }
    ],
    "body": null
   },
   {
    "name": "receipts-html",
    "method": "GET",
    "path": "/api/v1/plugipay/receipts/{id}/html",
    "summary": "List html",
    "pathParams": [
     "id"
    ],
    "query": [],
    "body": null
   },
   {
    "name": "receipts-pdf",
    "method": "GET",
    "path": "/api/v1/plugipay/receipts/{id}/pdf",
    "summary": "Binary receipt passthroughs — PDF, HTML, ESC/POS thermal.",
    "pathParams": [
     "id"
    ],
    "query": [],
    "body": null
   },
   {
    "name": "templates-preview",
    "method": "POST",
    "path": "/api/v1/plugipay/templates/preview",
    "summary": "Template preview returns raw HTML (not envelope JSON) — the generic catch-all below would try to JSON-parse it and throw.",
    "pathParams": [],
    "query": [],
    "body": []
   }
  ]
 },
 {
  "area": "portfolio",
  "routes": [
   {
    "name": "create",
    "method": "POST",
    "path": "/api/v1/portfolio",
    "summary": "Create a portfolio",
    "pathParams": [],
    "query": [],
    "body": [
     {
      "name": "title",
      "kind": "string",
      "required": true
     },
     {
      "name": "description",
      "kind": "string",
      "required": false
     },
     {
      "name": "images",
      "kind": "array",
      "required": false
     },
     {
      "name": "features",
      "kind": "string",
      "required": false
     },
     {
      "name": "serviceId",
      "kind": "string",
      "required": false
     },
     {
      "name": "externalUrl",
      "kind": "string",
      "required": false
     },
     {
      "name": "clientName",
      "kind": "string",
      "required": false
     },
     {
      "name": "completedAt",
      "kind": "string",
      "required": false
     },
     {
      "name": "published",
      "kind": "boolean",
      "required": false
     },
     {
      "name": "sortOrder",
      "kind": "number",
      "required": false
     }
    ]
   },
   {
    "name": "delete",
    "method": "DELETE",
    "path": "/api/v1/portfolio/{id}",
    "summary": "Delete a portfolio",
    "pathParams": [
     "id"
    ],
    "query": [],
    "body": null
   },
   {
    "name": "get",
    "method": "GET",
    "path": "/api/v1/portfolio/{id}",
    "summary": "Get a portfolio",
    "pathParams": [
     "id"
    ],
    "query": [],
    "body": null
   },
   {
    "name": "list",
    "method": "GET",
    "path": "/api/v1/portfolio",
    "summary": "List portfolio",
    "pathParams": [],
    "query": [],
    "body": null
   },
   {
    "name": "update",
    "method": "PATCH",
    "path": "/api/v1/portfolio/{id}",
    "summary": "Update a portfolio",
    "pathParams": [
     "id"
    ],
    "query": [],
    "body": [
     {
      "name": "title",
      "kind": "string",
      "required": false
     },
     {
      "name": "description",
      "kind": "string",
      "required": false
     },
     {
      "name": "images",
      "kind": "array",
      "required": false
     },
     {
      "name": "features",
      "kind": "string",
      "required": false
     },
     {
      "name": "serviceId",
      "kind": "string",
      "required": false
     },
     {
      "name": "externalUrl",
      "kind": "string",
      "required": false
     },
     {
      "name": "clientName",
      "kind": "string",
      "required": false
     },
     {
      "name": "completedAt",
      "kind": "string",
      "required": false
     },
     {
      "name": "published",
      "kind": "boolean",
      "required": false
     },
     {
      "name": "sortOrder",
      "kind": "number",
      "required": false
     }
    ]
   }
  ]
 },
 {
  "area": "public",
  "routes": [
   {
    "name": "create-orders-pay",
    "method": "POST",
    "path": "/api/v1/public/orders/{accessToken}/pay",
    "summary": "Buyer \"Pay online\" — Payment module path, LEGACY single payment.",
    "pathParams": [
     "accessToken"
    ],
    "query": [],
    "body": null
   },
   {
    "name": "create-orders-pay-2",
    "method": "POST",
    "path": "/api/v1/public/orders/{accessToken}/pay/{paymentId}",
    "summary": "Buyer \"Pay online\" for ONE installment of a split.",
    "pathParams": [
     "accessToken",
     "paymentId"
    ],
    "query": [],
    "body": null
   },
   {
    "name": "domains-provision-callback",
    "method": "POST",
    "path": "/api/v1/public/domains/provision-callback",
    "summary": "Create a provision callback",
    "pathParams": [],
    "query": [],
    "body": [
     {
      "name": "domain",
      "kind": "string",
      "required": true
     },
     {
      "name": "status",
      "kind": "string",
      "required": true,
      "choices": [
       "success",
       "failed"
      ]
     },
     {
      "name": "error",
      "kind": "string",
      "required": false
     }
    ]
   },
   {
    "name": "domains-resolve",
    "method": "GET",
    "path": "/api/v1/public/domains/resolve",
    "summary": "Host → storefront slug — used by the frontend middleware to route a custom domain to the right storefront. null for serront hosts / unknown.",
    "pathParams": [],
    "query": [
     {
      "name": "host",
      "kind": "string",
      "required": false
     }
    ],
    "body": null
   },
   {
    "name": "get-storefront-blog",
    "method": "GET",
    "path": "/api/v1/public/storefront/{slug}/blog/{postSlug}",
    "summary": "Single published post.",
    "pathParams": [
     "slug",
     "postSlug"
    ],
    "query": [],
    "body": null,
    "aliases": [
     "storefront-blog-2"
    ]
   },
   {
    "name": "orders",
    "method": "GET",
    "path": "/api/v1/public/orders/{accessToken}",
    "summary": "Get an order",
    "pathParams": [
     "accessToken"
    ],
    "query": [],
    "body": null
   },
   {
    "name": "orders-attachment",
    "method": "POST",
    "path": "/api/v1/public/orders/{accessToken}/attachment",
    "summary": "Chat attachment upload (tokenized guest page).",
    "pathParams": [
     "accessToken"
    ],
    "query": [],
    "body": null
   },
   {
    "name": "orders-claim-payment",
    "method": "POST",
    "path": "/api/v1/public/orders/{accessToken}/claim-payment",
    "summary": "Buyer \"I have transferred\". unpaid → payment_claimed; an already-claimed re-claim is a 200 no-op (storlaunch precedent); confirmed → 409.",
    "pathParams": [
     "accessToken"
    ],
    "query": [],
    "body": null
   },
   {
    "name": "orders-invoice-pdf",
    "method": "GET",
    "path": "/api/v1/public/orders/{accessToken}/invoice.pdf",
    "summary": "The order's Plugipay invoice PDF, streamed for the buyer.",
    "pathParams": [
     "accessToken"
    ],
    "query": [],
    "body": null
   },
   {
    "name": "orders-messages",
    "method": "POST",
    "path": "/api/v1/public/orders/{accessToken}/messages",
    "summary": "Messages an order",
    "pathParams": [
     "accessToken"
    ],
    "query": [],
    "body": [
     {
      "name": "body",
      "kind": "string",
      "required": true
     },
     {
      "name": "attachments",
      "kind": "array",
      "required": false
     }
    ]
   },
   {
    "name": "orders-messages-stream",
    "method": "GET",
    "path": "/api/v1/public/orders/{accessToken}/messages/stream",
    "summary": "SSE: realtime nudge for the tokenized guest order page.",
    "pathParams": [
     "accessToken"
    ],
    "query": [],
    "body": null
   },
   {
    "name": "orders-payments-claim-payment",
    "method": "POST",
    "path": "/api/v1/public/orders/{accessToken}/payments/{paymentId}/claim-payment",
    "summary": "Buyer \"I have transferred\" for ONE installment. unpaid → payment_claimed (+ aggregate recompute); re-claim is a 200 no-op; confirmed → 409.",
    "pathParams": [
     "accessToken",
     "paymentId"
    ],
    "query": [],
    "body": null
   },
   {
    "name": "orders-payments-proof",
    "method": "PUT",
    "path": "/api/v1/public/orders/{accessToken}/payments/{paymentId}/proof",
    "summary": "Per-installment manual-transfer proof — same 5MB + raster-image rules as the legacy order-level proof.",
    "pathParams": [
     "accessToken",
     "paymentId"
    ],
    "query": [],
    "body": [
     {
      "name": "length",
      "kind": "string",
      "required": false
     }
    ]
   },
   {
    "name": "orders-proof",
    "method": "PUT",
    "path": "/api/v1/public/orders/{accessToken}/proof",
    "summary": "Proof an order",
    "pathParams": [
     "accessToken"
    ],
    "query": [],
    "body": [
     {
      "name": "length",
      "kind": "string",
      "required": false
     }
    ]
   },
   {
    "name": "storefront",
    "method": "GET",
    "path": "/api/v1/public/storefront/{slug}",
    "summary": "Get a storefront",
    "pathParams": [
     "slug"
    ],
    "query": [],
    "body": null
   },
   {
    "name": "storefront-blog",
    "method": "GET",
    "path": "/api/v1/public/storefront/{slug}/blog",
    "summary": "Published posts list.",
    "pathParams": [
     "slug"
    ],
    "query": [],
    "body": null
   },
   {
    "name": "storefront-blog-rss-xml",
    "method": "GET",
    "path": "/api/v1/public/storefront/{slug}/blog/rss.xml",
    "summary": "RSS 2.0 feed of published posts.",
    "pathParams": [
     "slug"
    ],
    "query": [],
    "body": null
   },
   {
    "name": "storefront-legal",
    "method": "GET",
    "path": "/api/v1/public/storefront/{slug}/legal/{page}",
    "summary": "Get a legal",
    "pathParams": [
     "slug",
     "page"
    ],
    "query": [],
    "body": null
   },
   {
    "name": "storefront-order",
    "method": "POST",
    "path": "/api/v1/public/storefront/{slug}/order",
    "summary": "Order a storefront",
    "pathParams": [
     "slug"
    ],
    "query": [],
    "body": [
     {
      "name": "serviceSlug",
      "kind": "string",
      "required": true
     },
     {
      "name": "packageName",
      "kind": "string",
      "required": false
     },
     {
      "name": "buyerName",
      "kind": "string",
      "required": true
     },
     {
      "name": "buyerEmail",
      "kind": "string",
      "required": true
     },
     {
      "name": "buyerPhone",
      "kind": "string",
      "required": false
     },
     {
      "name": "preferredDate",
      "kind": "string",
      "required": false
     },
     {
      "name": "notes",
      "kind": "string",
      "required": false
     },
     {
      "name": "discountCode",
      "kind": "string",
      "required": false
     },
     {
      "name": "giftCardCode",
      "kind": "string",
      "required": false
     }
    ]
   },
   {
    "name": "storefront-pixels",
    "method": "GET",
    "path": "/api/v1/public/storefront/{slug}/pixels",
    "summary": "The storefront's ad-pixel IDs, for <PixelScripts/> on the public pages.",
    "pathParams": [
     "slug"
    ],
    "query": [],
    "body": null
   },
   {
    "name": "storefront-validate-discount",
    "method": "POST",
    "path": "/api/v1/public/storefront/{slug}/validate-discount",
    "summary": "Validate discount a storefront",
    "pathParams": [
     "slug"
    ],
    "query": [],
    "body": [
     {
      "name": "code",
      "kind": "string",
      "required": true
     },
     {
      "name": "priceIdr",
      "kind": "number",
      "required": true
     }
    ]
   }
  ]
 },
 {
  "area": "services",
  "routes": [
   {
    "name": "create",
    "method": "POST",
    "path": "/api/v1/services",
    "summary": "Create a service",
    "pathParams": [],
    "query": [],
    "body": [
     {
      "name": "slug",
      "kind": "string",
      "required": true
     },
     {
      "name": "name",
      "kind": "string",
      "required": true
     },
     {
      "name": "description",
      "kind": "string",
      "required": false
     },
     {
      "name": "shortDescription",
      "kind": "string",
      "required": false
     },
     {
      "name": "thumbnail",
      "kind": "string",
      "required": false
     },
     {
      "name": "coverImages",
      "kind": "array",
      "required": false
     },
     {
      "name": "tags",
      "kind": "array",
      "required": false
     },
     {
      "name": "leadTimeText",
      "kind": "string",
      "required": false
     },
     {
      "name": "requirementsText",
      "kind": "string",
      "required": false
     },
     {
      "name": "seoTitle",
      "kind": "string",
      "required": false
     },
     {
      "name": "seoDescription",
      "kind": "string",
      "required": false
     },
     {
      "name": "pricingType",
      "kind": "string",
      "required": true,
      "choices": [
       "fixed",
       "hourly",
       "package"
      ]
     },
     {
      "name": "priceIdr",
      "kind": "number",
      "required": false
     },
     {
      "name": "packages",
      "kind": "array",
      "required": false
     },
     {
      "name": "active",
      "kind": "boolean",
      "required": false
     },
     {
      "name": "sortOrder",
      "kind": "number",
      "required": false
     }
    ]
   },
   {
    "name": "delete",
    "method": "DELETE",
    "path": "/api/v1/services/{id}",
    "summary": "Delete a service",
    "pathParams": [
     "id"
    ],
    "query": [],
    "body": null
   },
   {
    "name": "get",
    "method": "GET",
    "path": "/api/v1/services/{id}",
    "summary": "Get a service",
    "pathParams": [
     "id"
    ],
    "query": [],
    "body": null
   },
   {
    "name": "list",
    "method": "GET",
    "path": "/api/v1/services",
    "summary": "List services",
    "pathParams": [],
    "query": [],
    "body": null
   },
   {
    "name": "update",
    "method": "PATCH",
    "path": "/api/v1/services/{id}",
    "summary": "Update a service",
    "pathParams": [
     "id"
    ],
    "query": [],
    "body": [
     {
      "name": "slug",
      "kind": "string",
      "required": false
     },
     {
      "name": "name",
      "kind": "string",
      "required": false
     },
     {
      "name": "description",
      "kind": "string",
      "required": false
     },
     {
      "name": "shortDescription",
      "kind": "string",
      "required": false
     },
     {
      "name": "thumbnail",
      "kind": "string",
      "required": false
     },
     {
      "name": "coverImages",
      "kind": "array",
      "required": false
     },
     {
      "name": "tags",
      "kind": "array",
      "required": false
     },
     {
      "name": "leadTimeText",
      "kind": "string",
      "required": false
     },
     {
      "name": "requirementsText",
      "kind": "string",
      "required": false
     },
     {
      "name": "seoTitle",
      "kind": "string",
      "required": false
     },
     {
      "name": "seoDescription",
      "kind": "string",
      "required": false
     },
     {
      "name": "pricingType",
      "kind": "string",
      "required": false,
      "choices": [
       "fixed",
       "hourly",
       "package"
      ]
     },
     {
      "name": "priceIdr",
      "kind": "number",
      "required": false
     },
     {
      "name": "packages",
      "kind": "array",
      "required": false
     },
     {
      "name": "active",
      "kind": "boolean",
      "required": false
     },
     {
      "name": "sortOrder",
      "kind": "number",
      "required": false
     }
    ]
   }
  ]
 },
 {
  "area": "storefront",
  "routes": [
   {
    "name": "list",
    "method": "GET",
    "path": "/api/v1/storefront",
    "summary": "List storefront",
    "pathParams": [],
    "query": [],
    "body": null
   },
   {
    "name": "set",
    "method": "PUT",
    "path": "/api/v1/storefront",
    "summary": "Set storefront",
    "pathParams": [],
    "query": [],
    "body": [
     {
      "name": "slug",
      "kind": "string",
      "required": true
     },
     {
      "name": "displayName",
      "kind": "string",
      "required": true
     },
     {
      "name": "tagline",
      "kind": "string",
      "required": false
     },
     {
      "name": "accentColor",
      "kind": "string",
      "required": false
     },
     {
      "name": "brandColor",
      "kind": "string",
      "required": false
     },
     {
      "name": "bio",
      "kind": "string",
      "required": false
     },
     {
      "name": "whatsappNumber",
      "kind": "string",
      "required": false
     },
     {
      "name": "manualBankAccounts",
      "kind": "array",
      "required": false
     },
     {
      "name": "manualInstructions",
      "kind": "string",
      "required": false
     },
     {
      "name": "businessPhone",
      "kind": "string",
      "required": false
     },
     {
      "name": "businessEmail",
      "kind": "string",
      "required": false
     },
     {
      "name": "businessAddress",
      "kind": "string",
      "required": false
     },
     {
      "name": "socialLinks",
      "kind": "json",
      "required": false
     },
     {
      "name": "bannerUrl",
      "kind": "string",
      "required": false
     },
     {
      "name": "logoUrl",
      "kind": "string",
      "required": false
     },
     {
      "name": "hideBranding",
      "kind": "boolean",
      "required": false
     },
     {
      "name": "published",
      "kind": "boolean",
      "required": false
     }
    ]
   }
  ]
 },
 {
  "area": "testimonials",
  "routes": [
   {
    "name": "create",
    "method": "POST",
    "path": "/api/v1/testimonials",
    "summary": "Create a testimonial",
    "pathParams": [],
    "query": [],
    "body": [
     {
      "name": "authorName",
      "kind": "string",
      "required": true
     },
     {
      "name": "authorRole",
      "kind": "string",
      "required": false
     },
     {
      "name": "quote",
      "kind": "string",
      "required": true
     },
     {
      "name": "rating",
      "kind": "number",
      "required": false
     },
     {
      "name": "avatarUrl",
      "kind": "string",
      "required": false
     },
     {
      "name": "serviceId",
      "kind": "string",
      "required": false
     },
     {
      "name": "published",
      "kind": "boolean",
      "required": false
     },
     {
      "name": "sortOrder",
      "kind": "number",
      "required": false
     }
    ]
   },
   {
    "name": "delete",
    "method": "DELETE",
    "path": "/api/v1/testimonials/{id}",
    "summary": "Delete a testimonial",
    "pathParams": [
     "id"
    ],
    "query": [],
    "body": null
   },
   {
    "name": "get",
    "method": "GET",
    "path": "/api/v1/testimonials/{id}",
    "summary": "Get a testimonial",
    "pathParams": [
     "id"
    ],
    "query": [],
    "body": null
   },
   {
    "name": "list",
    "method": "GET",
    "path": "/api/v1/testimonials",
    "summary": "List testimonials",
    "pathParams": [],
    "query": [],
    "body": null
   },
   {
    "name": "update",
    "method": "PATCH",
    "path": "/api/v1/testimonials/{id}",
    "summary": "Update a testimonial",
    "pathParams": [
     "id"
    ],
    "query": [],
    "body": [
     {
      "name": "authorName",
      "kind": "string",
      "required": false
     },
     {
      "name": "authorRole",
      "kind": "string",
      "required": false
     },
     {
      "name": "quote",
      "kind": "string",
      "required": false
     },
     {
      "name": "rating",
      "kind": "number",
      "required": false
     },
     {
      "name": "avatarUrl",
      "kind": "string",
      "required": false
     },
     {
      "name": "serviceId",
      "kind": "string",
      "required": false
     },
     {
      "name": "published",
      "kind": "boolean",
      "required": false
     },
     {
      "name": "sortOrder",
      "kind": "number",
      "required": false
     }
    ]
   }
  ]
 },
 {
  "area": "uploads",
  "routes": [
   {
    "name": "attachment",
    "method": "POST",
    "path": "/api/v1/uploads/attachment",
    "summary": "Chat attachment upload (seller side).",
    "pathParams": [],
    "query": [],
    "body": null
   },
   {
    "name": "from-run-media",
    "method": "POST",
    "path": "/api/v1/uploads/from-run-media",
    "summary": "Create a from run media",
    "pathParams": [],
    "query": [],
    "body": [
     {
      "name": "filename",
      "kind": "string",
      "required": false
     },
     {
      "name": "runId",
      "kind": "string",
      "required": false
     }
    ]
   },
   {
    "name": "from-url",
    "method": "POST",
    "path": "/api/v1/uploads/from-url",
    "summary": "Url { url } Re-host a public image onto our own storage and return the durable URL.",
    "pathParams": [],
    "query": [],
    "body": [
     {
      "name": "url",
      "kind": "string",
      "required": false
     }
    ]
   },
   {
    "name": "image",
    "method": "POST",
    "path": "/api/v1/uploads/image",
    "summary": "Create an image",
    "pathParams": [],
    "query": [],
    "body": null
   }
  ]
 },
 {
  "area": "webhook-subscriptions",
  "routes": [
   {
    "name": "create",
    "method": "POST",
    "path": "/api/v1/webhook-subscriptions",
    "summary": "Register an endpoint.",
    "pathParams": [],
    "query": [],
    "body": [
     {
      "name": "url",
      "kind": "string",
      "required": true
     },
     {
      "name": "events",
      "kind": "array",
      "required": false
     }
    ]
   },
   {
    "name": "delete",
    "method": "DELETE",
    "path": "/api/v1/webhook-subscriptions/{id}",
    "summary": "Delete a webhook subscription",
    "pathParams": [
     "id"
    ],
    "query": [],
    "body": null
   },
   {
    "name": "deliveries",
    "method": "GET",
    "path": "/api/v1/webhook-subscriptions/deliveries",
    "summary": "List webhook deliveries.",
    "pathParams": [],
    "query": [
     {
      "name": "limit",
      "kind": "number",
      "required": false
     },
     {
      "name": "cursor",
      "kind": "string",
      "required": false
     },
     {
      "name": "subscriptionId",
      "kind": "string",
      "required": false
     },
     {
      "name": "status",
      "kind": "string",
      "required": false,
      "choices": [
       "pending",
       "succeeded",
       "failed"
      ]
     },
     {
      "name": "type",
      "kind": "string",
      "required": false
     }
    ],
    "body": null
   },
   {
    "name": "deliveries-retry",
    "method": "POST",
    "path": "/api/v1/webhook-subscriptions/deliveries/{id}/retry",
    "summary": "Retry a webhook delivery.",
    "pathParams": [
     "id"
    ],
    "query": [],
    "body": null
   },
   {
    "name": "event-types",
    "method": "GET",
    "path": "/api/v1/webhook-subscriptions/event-types",
    "summary": "The event types a subscription can receive, with what each one means.",
    "pathParams": [],
    "query": [],
    "body": null
   },
   {
    "name": "get-deliveries",
    "method": "GET",
    "path": "/api/v1/webhook-subscriptions/deliveries/{id}",
    "summary": "Get a webhook delivery, with every attempt made at it.",
    "pathParams": [
     "id"
    ],
    "query": [],
    "body": null
   },
   {
    "name": "list",
    "method": "GET",
    "path": "/api/v1/webhook-subscriptions",
    "summary": "List webhook subscriptions",
    "pathParams": [],
    "query": [],
    "body": null
   },
   {
    "name": "update",
    "method": "PATCH",
    "path": "/api/v1/webhook-subscriptions/{id}",
    "summary": "Update a subscription. `active: false` pauses it (its queued deliveries become failed); `active: true` re-enables it — also after Serront switched it off for failing — and clears its failure streak.",
    "pathParams": [
     "id"
    ],
    "query": [],
    "body": [
     {
      "name": "url",
      "kind": "string",
      "required": false
     },
     {
      "name": "events",
      "kind": "array",
      "required": false
     },
     {
      "name": "active",
      "kind": "boolean",
      "required": false
     }
    ]
   }
  ]
 }
];

// A field whose flag would clash with this command's own options or the CLI's global ones
// is given as --field-<name>.
const RESERVED = new Set(['help', 'version', 'json', 'profile', 'api', 'on-behalf-of', 'color', 'no-color', 'body-json']);
const plain = (name: string): string => name.replace(/([a-z0-9])([A-Z])/g, '$1-$2').replace(/_/g, '-').toLowerCase();
const flag = (name: string): string => (RESERVED.has(plain(name)) ? `field-${plain(name)}` : plain(name));
const camel = (name: string): string => flag(name).replace(/-([a-z0-9])/g, (_, c: string) => c.toUpperCase());

function value(field: Field, raw: string): unknown {
  if (field.kind === 'number') {
    const n = Number(raw);
    if (Number.isNaN(n)) throw new Error(`--${flag(field.name)} must be a number`);
    return n;
  }
  if (field.kind === 'boolean') return raw === '' || raw === 'true' || raw === '1' || raw === 'yes';
  if (field.kind === 'array') return raw.trim().startsWith('[') ? JSON.parse(raw) : raw.split(',').map((x) => x.trim()).filter(Boolean);
  if (field.kind === 'json') return JSON.parse(raw);
  if (field.choices && !field.choices.includes(raw)) throw new Error(`--${flag(field.name)} must be one of: ${field.choices.join(', ')}`);
  return raw;
}

export function buildApiCommand(): Command {
  const api = new Command('api').description('Every route of the API, one command each (generated from the API spec)');
  for (const { area, routes } of API_ROUTES) {
    const group = new Command(area).description(`${area} routes`);
    for (const route of routes) {
      for (const name of [route.name, ...(route.aliases ?? [])]) {
      const cmd = new Command(name).description(`${route.summary} (${route.method} ${route.path})`);
      for (const p of route.pathParams) cmd.argument(`<${p}>`);
      const fields = [...route.query, ...(route.body ?? [])];
      for (const f of fields) {
        const hint = f.choices ? ` (${f.choices.join('|')})` : f.kind === 'json' || f.kind === 'array' ? ` (${f.kind})` : '';
        cmd.option(f.kind === 'boolean' ? `--${flag(f.name)} [value]` : `--${flag(f.name)} <value>`, `${f.required ? 'required' : 'optional'}${hint}`);
      }
      if (route.body) cmd.option('--body-json <json>', 'the whole body as JSON (fields given as flags override it)');
      cmd.action(async (...parts: unknown[]) => {
        const command = parts[parts.length - 1] as Command;
        const opts = command.opts() as Record<string, string | boolean | undefined>;
        try {
        let path = route.path;
        route.pathParams.forEach((p, i) => { path = path.replace(`{${p}}`, encodeURIComponent(String(parts[i]))); });
        const query: Record<string, unknown> = {};
        for (const f of route.query) {
          const raw = opts[camel(f.name)];
          if (raw !== undefined) query[f.name] = value(f, raw === true ? '' : String(raw));
        }
        let body: Record<string, unknown> | undefined;
        if (route.body) {
          body = opts.bodyJson ? (JSON.parse(String(opts.bodyJson)) as Record<string, unknown>) : {};
          for (const f of route.body) {
            const raw = opts[camel(f.name)];
            if (raw !== undefined) body[f.name] = value(f, raw === true ? '' : String(raw));
          }
          const missing = route.body.filter((f) => f.required && body![f.name] === undefined).map((f) => `--${flag(f.name)}`);
          if (missing.length) throw new Error(`missing ${missing.join(', ')}`);
        }
        await callRoute(command, route.method, path, query, body);
        } catch (err) {
          await failRoute(command, err);
        }
      });
      group.addCommand(cmd, { hidden: name !== route.name });
      }
    }
    api.addCommand(group);
  }
  return api;
}
